#version: '3.8'
#
#services:
#  zookeeper:
#    image: bitnami/zookeeper:latest
#    ports:
#      - "2182:2181"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#
#  kafka:
#    image: bitnami/kafka:latest
#    ports:
#      - "9093:9092"
#    environment:
#      - KAFKA_BROKER_ID=2
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
#
#  postgres:
#    image: postgres:15
#    container_name: consumer_postgres
#    ports:
#      - "5433:5432"
#    environment:
#      POSTGRES_DB: camel_db
#      POSTGRES_USER: camel_user
#      POSTGRES_PASSWORD: camel_pass
#
#  consumer-service:
#    image: consumer-service:latest
#    container_name: consumer-service
#    build:
#      context: ./consumer
#    depends_on:
#      - kafka
#      - postgres
#    ports:
#      - "8082:8082"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/camel_db
#      SPRING_DATASOURCE_USERNAME: camel_user
#      SPRING_DATASOURCE_PASSWORD: camel_pass
#      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
